layout_spectrum: 0.4385329
typography_spectrum: 0.1540104
color:
  saturation: 0.1075503
  lightness: 0.4810955
  brandStrength: 0.2536809
  rhythmicContrast: 0.305536
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
name: Studio9
